# Generated by Django 5.0.6 on 2024-06-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findstaff', '0003_rename_house_name_room_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findstaff.room')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
